import { Inter } from "next/font/google";
import Header from "@/app/components/header"
import Footer from "@/app/components/footer";
import Hero from "@/app/components/hero"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Hero/>
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  );
}
